### ISSUE TITLE
Problem with colon

### ISSUE THREAD

**Issue by Technochips** [EldinZenderink/SimpleIRCLib#1]
Hi so i used this, but it seem that any received message that has a colon in it is cut in half

Message writed:

> So i made this: blah blah you should check it out

Message received with this library

> So i made this

Can you fix it? Thanks

**Comment by RareAMV** [comment]
I will try to fix it up comming weekend, thanks for reporting :D

**Comment by EldinZenderink** [comment]
I will try to look at this issue upcoming weekend, thanks for reporting!
