### ISSUE TITLE
Chat Messages using the form example

### ISSUE THREAD

**Issue by Og1Kenobi** [EldinZenderink/SimpleIRCLib#2]
When sending a message to an irc channel from this client it will succeed and the channel can see the message. When you send a message to the channel from another client this client can not see the message.

**Comment by EldinZenderink** [comment]
I would like a copy from the debug window, because it could be a message parsing error inside the library, which I only can solve with the help of the debug window. Also, are you using a private/local server. Could you send me details about the server you are trying to connect to? That would be very helpful.

**Comment by Og1Kenobi** [comment]
ircd-hybrid-8.2.17
![simpleirc](https://cloud.githubusercontent.com/assets/18406354/14768502/d3015a26-0a09-11e6-82b2-ef3380bd38db.PNG)

**Comment by Og1Kenobi** [comment]
it is a local irc server i stood up to test this before i embed it

**Comment by EldinZenderink** [comment]
Ok, I will have a look at this, i am not sure if i will be able to fix it today, but i certainly will try.

**Comment by Og1Kenobi** [comment]
That would be great! I also noticed that after push send the message I just typed is still in the box so I have to backspace the old message in order enter a new message

**Comment by EldinZenderink** [comment]
I fixed both chat and dcc issues (atleast they appear to be fixed on my end). For messages that stay in the message to send textbox, thats something that has to be coded around the library and cannot be done from within. What you could do is this (when you named the textbox for sending messages 'MessageTextBox': `MessageTextBox.Text = ""` when you press the send button. Same goes for the enter key event on the MessageTextBox, if you set any. I will commit the changes in a minute. Thanks for telling me about these issues!

**Comment by Og1Kenobi** [comment]
that chat issue has been fixed. I will post the issue with DCC transfer on the other thread
