### ISSUE TITLE
DCC when using the form example

### ISSUE THREAD

**Issue by Og1Kenobi** [EldinZenderink/SimpleIRCLib#3]
When sending a file to this client via DCC it will consistently fail at 95% according to this clients debug. The sending client show a successful send.

**Comment by EldinZenderink** [comment]
And the file? Was the file correctly downloaded?

**Comment by Og1Kenobi** [comment]
Using mIRC it shows transfer complete.  simpleirc debug says :+1: 

New Filename: plot.log

 newFileName(without illigal chars): plot.log

New Filename: plot.log

 newIpBW: 167772179

 DCC SERVER REPLY: :jdouglas!jdouglas@iWedge.verticalliquid.com PRIVMSG MrTester :DCC SEND plot.log 167772179 1024 537

 FILENAME: plot.log

 FILESIZE: 537

 IP: 10.0.0.19

 PORT: 1024

 PACK: 
File does not exist yet, start connection 

 BOT: 
Download stopped at < 95 % finished, deleting file: plot.log 

File has been downloaded! 
 File Location:C:\Users\Jonathan\Documents\Visual Studio 2015\Projects\SimpleIRCLib-master\FormExample\bin\Debug\plot.log

This happens even if i change the download directory etc

**Comment by EldinZenderink** [comment]
Ok, that is probably my fault, I only tested this library with big files, forgot about the small stuff, my apologie, will try to fix this as soon as possible as well

**Comment by Og1Kenobi** [comment]
No worries.

**Comment by EldinZenderink** [comment]
The dcc problem for downloading small files has been fixed, atleast it appears to work on my end. Please tell me your findings so that we can close these issues!

**Comment by Og1Kenobi** [comment]
![irc1](https://cloud.githubusercontent.com/assets/18406354/14769380/9ef5f440-0a1c-11e6-8bb7-f8baa181f024.PNG)
![irc2](https://cloud.githubusercontent.com/assets/18406354/14769381/a37a4b06-0a1c-11e6-92c1-445592efe19f.PNG)

**Comment by EldinZenderink** [comment]
Hmmm, weird, must be a really reaaally tiny file you are sending their... ok, will try to sort it out, i will close the other issue :D, sorry for asking this much, but unfortunately the debug form is scrolled all the way up in your screenshot (me stupid for just noticing), could you try again and scroll down in the debug window? Atleast until you see a message that goes something like this: 

> Something went wrong while downloading the file! Removing from xdcc que to be sure! Error:

This message will appear after starting a dcc download, when it fails to download.
That message is hopefully going to tell me about the issue at hand. Without it, I can only guess.

Edit: I might not come around to fixing this issue this evening, I will not be able to respond quickly either. If do get to fixing it, it will be late in the evening unfortunately.
