### ISSUE TITLE
NICKSERV IDENTIFY

### ISSUE THREAD

**Issue by AMONRA75** [EldinZenderink/SimpleIRCLib#5]
hi,

how indentify to NICKSERV?

irc command is   --->   "/msg NickServ IDENTIFY password"

best regards

**Comment by EldinZenderink** [comment]
For now its not yet possible... the user cant send / messages, I think I might add a way to create those commands yourself. There are more missing commands. Will also add a way to play with the raw data. I will do it tomorrow so check back by then ^^.

**Comment by EldinZenderink** [comment]
Right, as said, I have made it possible to send /msg messages. So NickServ should work. Added also support for NOTICE messages, it's now being parsed just like PRIVMSG messages, output looks like: NickServ: bla bla bla. If you need anything else more specific, you can send raw messages to the server with the sendRawMessage function. You can add a callback for the raw server output if the return message of the server does not contain PRIVMSG or NOTICE. See ReadMe for more about that.

**Comment by AMONRA75** [comment]
great!
i try this
tnx a lot!
