### ISSUE TITLE
dcc download

### ISSUE THREAD

**Issue by AMONRA75** [EldinZenderink/SimpleIRCLib#6]
hi,

i need example for download a file with dcc
please help me

best regards

**Comment by EldinZenderink** [comment]
Hi, I am not really sure what you mean, a very simple example using console can be found here: [Console Test Code](https://github.com/EldinZenderink/SimpleIRCLib/blob/master/IrcLibTest/Program.cs)

You just need to create a method that will run whenever there is an update on your download. Commands and such can be found in the readme.

For initiating a download, just send a: `/msg botname xdcc send #packnumber ` message with the sendMessage function.

For a more detailed tutorial about downloading from a bot using xdcc (dcc) can be found here; https://en.wikibooks.org/wiki/Downloading_Files_from_IRC/XDCC_Bot_Guide

As mentioned this a very simple library only tested with downloading from bots. 

Hope this helps, if not, I will help where I can. But be as clear as possible when you describe your problem, as I can't look into your brain (unfortunately ;) ).

**Comment by AMONRA75** [comment]
tnx a lot!
